name: build GitBook & deploy to Gitee

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 1. Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.23.0
    - name: 2. Cache node modules
      uses: actions/cache@v1
      with:
       path: ~/.npm
       key: ${{ runner.os }}-node10-${{ hashFiles('**/book.json') }}        
    - name: 3. install & build
      run: |
       sudo npm install -g gitbook-cli
       gitbook install
       gitbook build
       mv book.pdf _book

    - name: 4. Configure Private Key
      env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
          SSH_PUB_KEY: ${{secrets.GITEE_RSA_PUB_KEY}}
      run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          echo "$SSH_PUB_KEY" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
        
    - name: 5. Push _book to Gitee
      env: 
        PROJ_PATH: ${{github.workspace}} 
        GITEE_REPO: git@gitee.com:wsj0051/wsj0051.git
      
      run: |
        cd ${PROJ_PATH}/_book/
        git init 
        git config user.email "wsj0051@163.com" 
        git config user.name "wsj0051" 
        git remote add origin ${GITEE_REPO}
        echo remote
        git add . 
        git commit -m "Updated By Github Actions With Build ${{github.run_number}} of ${{github.workflow}} For Github Pages" 
        git push --force --quiet origin master
          

    - name: 6. Deploy Gitee Pages
      uses: yanglbme/gitee-pages-action@main
      with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: wsj0051
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
          gitee-repo: wsj0051/wsj0051
          # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
          branch: master
